-- Crear tipos ENUM personalizado
CREATE TYPE tipo_carrera AS ENUM (
    'Ing. Software', 
    'Ing. Industrial', 
    'Ing. Tecnologias de la Informacion', 
    'Ing. Telecomunicaciones', 
    'Ing. en Automatizacion y Robotica'
);

CREATE TYPE tipo_modalidad AS ENUM ('Gratis', 'Pagado');

CREATE TYPE estado_pago AS ENUM ('Pendiente', 'Pagado');

CREATE TYPE asistencia_enum AS ENUM ('Presente', 'Ausente');

-- Tabla ROLES
CREATE TABLE ROLES (
    ID_ROL SERIAL PRIMARY KEY,
    NOM_ROL VARCHAR(100),
    DES_ROL TEXT
);

-- Tabla USUARIOS
CREATE TABLE USUARIOS (
    CED_USU VARCHAR(20) PRIMARY KEY,        
    NOM_PRI_USU VARCHAR(100) NOT NULL,
    NOM_SEG_USU VARCHAR(100) NOT NULL,
    APE_PRI_USU VARCHAR(100) NOT NULL,
    APE_SEG_USU VARCHAR(100) NOT NULL,
    COR_USU VARCHAR(255) NOT NULL UNIQUE,
    PAS_USU VARCHAR(255) NOT NULL,
    TEL_USU VARCHAR(20) NOT NULL,
    DIR_USU VARCHAR(200) NOT NULL,
    FEC_NAC_USU DATE NOT NULL,
    ID_ROL_USU INT,
    CAR_USU tipo_carrera,
    FOREIGN KEY (ID_ROL_USU) REFERENCES ROLES(ID_ROL)
);

-- Tabla EVENTOS_CURSOS
CREATE TABLE EVENTOS_CURSOS (
    ID_EVE_CUR SERIAL PRIMARY KEY,
    TIT_EVE_CUR VARCHAR(100) NOT NULL,
    DES_EVE_CUR TEXT,
    FEC_INI_EVE_CUR DATE NOT NULL,
    FEC_FIN_EVE_CUR DATE NOT NULL,
    COS_EVE_CUR DECIMAL(10,2) NOT NULL,
    MOD_EVE_CUR tipo_modalidad NOT NULL
);

-- Tabla INSCRIPCIONES
CREATE TABLE INSCRIPCIONES (
    ID_INS SERIAL PRIMARY KEY,
    CED_USU VARCHAR(20) NOT NULL,
    ID_EVE_CUR INT NOT NULL,
    FEC_INI_INS DATE NOT NULL,
    FEC_CIE_INS DATE NOT NULL,
    EST_PAG_INS estado_pago NOT NULL,
    FOREIGN KEY (CED_USU) REFERENCES USUARIOS(CED_USU),
    FOREIGN KEY (ID_EVE_CUR) REFERENCES EVENTOS_CURSOS(ID_EVE_CUR)
);

-- Tabla PAGOS
CREATE TABLE PAGOS (
    ID_PAG SERIAL PRIMARY KEY,
    ID_INS INT NOT NULL,
    FEC_PAG DATE NOT NULL,
    MON_PAG DECIMAL(10,2) NOT NULL,
    MET_PAG VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_INS) REFERENCES INSCRIPCIONES(ID_INS)
);

-- Tabla NOTAS_ASISTENCIAS
CREATE TABLE NOTAS_ASISTENCIAS (
    ID_NOT_ASI SERIAL PRIMARY KEY,
    ID_INS INT NOT NULL,
    NOT_FIN_NOT_ASI DECIMAL(5,2),
    ASI_NOT_ASI asistencia_enum,
    FOREIGN KEY (ID_INS) REFERENCES INSCRIPCIONES(ID_INS)
);

-- Tabla DE CERTIFICADOS
CREATE TABLE CERTIFICADOS (
    ID_CER SERIAL PRIMARY KEY,
    ID_INS INT NOT NULL,
    FEC_EMI_CER DATE NOT NULL,
    FOREIGN KEY (ID_INS) REFERENCES INSCRIPCIONES(ID_INS)
);